### ISSUE TITLE
support for velocity #foreach construct

### ISSUE THREAD

**Issue by jhn134910** [tocco/extjs3-ckeditor-extension#1]
If I take a HTML template with a velocity #foreach template like the following : 

<html>
   \n\n
   <p>Dear All,</p>
   \n\n
   <p>\n
   <table border=\"0\" cellspacing=\"0\" cellpadding=\"4\">
      \n
      <tr>
         <td>Contact Name:</td>
         <td>${contactName}</td>
      </tr>
      \n
      <tr>
         <td>Contact Phone Number:</td>
         <td>${contactPhoneNumber}</td>
      </tr>
      \n
      <tr>
         <td>Contact Email:</td>
         <td>${contactEmail}</td>
      </tr>
      \n
      <tr>
         <td>Preferred Collection Date:</td>
         <td>${preferredCollectionDate}</td>
      </tr>
      \n
      <tr>
         <td>Special Instructions:</td>
         <td>${specialInstructions}</td>
      </tr>
      \n
      <tr>
         <td style=\"vertical-align:top\">Collection Address:</td>
         <td>${collectionAddressLine1}<br />\n${collectionAddressLine2}<br />\n${collectionAddressLine3}<br />\n${collectionAddressLine4}<br />\n${postCode}<br />${city}<br />\n${country}<br /></td>
      </tr>
      \n
   </table>
   \n</p>\n<br />\n
   <p>\n
   <table border=\"0\" cellspacing=\"0\" cellpadding=\"4\" style=\"width:100%\">
      \n
      <tr><td style=\"font-weight:bold; border-top: 1px double #808080; border-bottom: 1px double #808080; border-left: 1px double #808080; border-right: none; padding-top: 0.04in; padding-bottom: 0.04in; padding-left: 0.04in; padding-right: 2px\">Serial Number</td>\n<td style=\"font-weight:bold; border-top: 1px double #808080; border-bottom: 1px double #808080; border-left: 1px double #808080; border-right: none; padding-top: 0.04in; padding-bottom: 0.04in; padding-left: 0.04in; padding-right: 2px\">Site Number</td>\n<td style=\"font-weight:bold; border: 1px double #808080; padding: 0.04in\">Study Name</td>\n</tr>
      \n#foreach($orderItem in $orderItems)\n
      <tr><td style=\"border-top: 1px double #808080; border-bottom: 1px double #808080; border-left: 1px double #808080; border-right: none; padding-top: 0.04in; padding-bottom: 0.04in; padding-left: 0.04in; padding-right: 2px\">$orderItem.serial</td><td style=\"border-top: 1px double #808080; border-bottom: 1px double #808080; border-left: 1px double #808080; border-right: none; padding-top: 0.04in; padding-bottom: 0.04in; padding-left: 0.04in; padding-right: 2px\">$orderItem.site</td><td style=\"border: 1px double #808080; padding: 0.04in\">$orderItem.study</td></tr>
      \n#end\n
   </table>
   \n</p>\n
   <p>\nRegards,\n</p>
   \n
</html>

and then I use the site : https://rawgit.com/tocco/extjs3-ckeditor-extension/master/example/ckeditor.html to view the value of this text, the velocity #foreach construct gets broken. Is there anyway to avoid this and to support the velocity #foreach construct.

**Comment by jhn134910** [comment]
Actually it breaks on submission of issue also. The #foreach statement is originally around a table row, but when previewed the #foreach statement is taken outside of the table and therefore the velocity variables in the table are out of scope and not resolved.

**Comment by uwolfer** [comment]
@jhn134910: This is not an issue which is introduced by this extension. You can also reproduce it with a plain CKEditor instance: http://ckeditor.com/demo

You might want to look into the following discussion in CKEditor forum: http://ckeditor.com/forums/CKEditor/CK-Editor-to-preserve-non-html-text
