### ISSUE TITLE
Problem with the destroyInstance.createDelegate()

### ISSUE THREAD

**Issue by lisdey89** [tocco/extjs3-ckeditor-extension#2]
Hello, 
First of all thanks for sharing this extension, I'm trying to use it and I have to say that I'm really new with Extjs, so here is my problem. I'm trying to adapt your extension to use it with Extjs 6, but I get this error: Exception: this.destroyInstance.createDelegate is not a function, I'm dont know very well what to do or how to replace this code, could anyone help me? 

Thanks in advance

**Comment by uwolfer** [comment]
@lisdey89: This extension works with Ext JS 3 only. Things have changed in Ext JS a lots in the last years - so getting this extension working with version 6 probably needs quite some efforts. Probably you can find a CKEditor extension which is built for Ext JS 6.
